# Generated by Django 2.2.5 on 2020-04-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disp_data', '0002_auto_20200421_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student1',
            name='res_id',
            field=models.IntegerField(),
        ),
    ]
