# Generated by Django 2.2.5 on 2020-04-21 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disp_data', '0003_auto_20200421_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student1',
            new_name='Student2',
        ),
    ]
